[build]
  command = "npm run build"
 


[[plugins]]
  package = "@netlify/plugin-nextjs"

# This redirects _next/data to be treated as static assets
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200
